### PR TITLE
Added name of query argument to custom parser

### PR DESCRIPTION
**Pull request by borispovod**

### CODE REVIEW

**Comment by sibnerian** [comment]
Interdasting. What's your intended use case for this? It seems weird to pass in an unused argument to the parse function.

I can see it being useful to protect certain keys from being parsed, but I'm not sure what else it would be good for (that's within the super-specific scope of this package).

**Comment by borispovod** [comment]
I have big numbers - ids, but i pass it as string, sometimes i need to check, that it's id and don't parse it.
ParseInt parse some strings like: "01".

**Comment by mariusc23** [comment]
Thanks for the PR! I could see this being useful. I ran into the same issue with mongo IDs getting parsed.

I merged it manually to get rid of the .idea files. You might want to add `.idea` to your [global gitignore file](https://help.github.com/articles/ignoring-files/).

**Comment by mariusc23** [comment]
Published v1.0.1 which includes this change.

**Pull request closed without merging**
